### PR TITLE
removed .git from package name

### PR DESCRIPTION
**Pull request by initconf**

### CODE REVIEW

**Comment by initconf** [comment]
Seth rightfully pointed out that I had .git in package names.

**Comment by initconf** [comment]
Hate to bother, finally decided on a meaningful package name - trying to avoid conflicts on two very similar packages (one with postgres dependency and other standalone)

**Comment by JustinAzoff** [comment]
It looks like you removed .git instead of \.git so all of your urls are now

https:/hub.com/

**Comment by 0xxon** [comment]
Yup, I just wanted to point that out too. Do you just want to make a new pull-request based on master that fixes them correctly? :)

**Comment by initconf** [comment]
OK I have fixed the typos. Could you please merge

**Pull request merged**
