### PR TITLE
Create bro-pkg.index

### PR DESCRIPTION
**Pull request by fatemabw**

### CODE REVIEW

**Comment by 0xxon** [comment]
Well, this was closed again faster than I could react to it ;).

In any case - could you please add a license to your repository at https://github.com/fatemabw/bro-inventory-scripts? We require that for everything added to the package manager; afterwards, if you re-open/re-create a pull request I will gladly merge it.

**Comment by fatemabw** [comment]
Ah, sorry about that... will add the licence.. reopened it :) (still new to how GitHub works)

**Comment by fatemabw** [comment]
Added the License.. can I close the pull request?..

**Comment by 0xxon** [comment]
No, the pull-request will be closed by us once it is added :)

**Comment by fatemabw** [comment]
Okie.. It was giving me the option to close the pull request, that's why asked, and that's why closed it the first time.. :)

Thanks!!

**Pull request merged**
