### PR TITLE
hope I did this right this time

### PR DESCRIPTION
**Pull request by theflakes**
Sorry, haven't worked with Git much.  Please let me know if I missed something and sorry for the last one.

### CODE REVIEW

**Comment by 0xxon** [comment]
Thanks, that looks great :)

Could you please also add a license to your repository, and potentially squash this pull request down to a single commit?

**Comment by theflakes** [comment]
Done, I think

**Comment by 0xxon** [comment]
Actualy, now you somehow modified a bunch of commits of other people and they have other hashes.

The easiest way to fix that is probably to just copy your file out, clone a new copy and add it there. Or - if you don't mind, I can also just copy your index file for you.

**Comment by theflakes** [comment]
Ugh, sorry.  Obviously a novice here.  I just cloned a new copy.

**Comment by 0xxon** [comment]
Thanks, merged your other pull request

**Pull request closed without merging**
